# This file is used to define and document your source datasets. 
# For dbt to be able to reference these datasets in models, they need to be well-defined in this file.

version: 2

sources:
  - name: nyc_restaurants  # This is the logical name
    database: your_database_name  # Optional, if you have specified a database
    schema: your_schema_name  # The schema where your source tables are
    tables:
      - name: action_table
      - name: violation_table
        description: "Details of violations found during inspections."
      - name: date_table
      - name: location_table
      - name: restaurant_table
      - name: facts_source_table
        description: "Source table for the facts data."
